In [1]:
import numpy as np

x = np.array([1,2,3,4,5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int32')

In [4]:
x.shape

(5,)

In [5]:
# rank 2 array
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
Y.shape

(4, 3)

In [7]:
Y.size

12

In [8]:
x = np.array(['Hello','World'])
print(x)

['Hello' 'World']


In [10]:
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [11]:
#numPy arrays must use elements of the same type
x = np.array([1,2,'World'])
print(x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)

['1' '2' 'World']
shape: (3,)
type: <class 'numpy.ndarray'>
dtype: <U11


In [12]:
# numPy up casts to a type, up casts integer to float in mixed element type array above
# you can specifiy dtype in array line x = np.array([1,2.4, 4], dtype=np.int64)
x = np.array([1, 2.4, 4])
print(x, x.dtype)

[1.  2.4 4. ] float64


In [14]:
x = np.array([1,2,3,4])
np.save('my_array',x)

In [15]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4]


In [19]:
# create 4 col x 3 row array, defaults to float64 and ,dtype=int to change default
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
print('dtype:', x.dtype)

dtype: float64


In [20]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#full creates with a constant
x = np.full([4,5], 5)
print(x)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [22]:
print(x.dtype)

int32


In [24]:
# identity matrix, has ones on the diagonal starts top left, all are square.
# use single integer argument.
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# diag takes the inputs as the diagonal and fills rest in with zeros
x = np.diag([10,20,30,50])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [26]:
x = np.arange(10)
print(x)
# takes up to 3 arguments, 
#1 integer is stop exclusive so -1, 
#2 integers start (incl) & stop (excl), 
#3 integers start (incl) & stop (excl) & step (default is 1)
# if use float not always precise due to finite floating point precision

[0 1 2 3 4 5 6 7 8 9]


In [27]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [30]:
x = np.arange(4,16,2)
print(x)

[ 4  6  8 10 12 14]


In [32]:
# for non integer step use linspace (n spaces), 
# must have 2 arguments start, stop, if n not specified defaults to 50
# stop is inclusive, can make it like arange if use  ,endpoint = False
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [33]:
x = np.linspace(0,25,10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [35]:
x= np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
# to convert any numPy array into a specified shape
# new shape has to be compatible with numnber of elements in the array.
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [38]:
x = np.linspace(0,50,10,endpoint=False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [39]:
# need to use random arrays in neural networks goes from 0 inclusive to 1 exclusive
x = np.random.random((3,3))
print(x)

[[0.42583134 0.86528512 0.3235146 ]
 [0.1176507  0.97346883 0.14052361]
 [0.79067111 0.70596865 0.68266308]]


In [40]:
# random integer array lower bound, upper bound and shape
x = np.random.randint(4, 15, (3,2))
print(x)

[[13  8]
 [ 9 11]
 [10  9]]


In [41]:
# sometimes need arrays with random numbers that satisfy statistical props, 
# i.e might need array the averages to zero
# this creates random floats drawn from a normal distribution with mean zero, stdev 0.1
x = np.random.normal(0, 0.1, size=(1000,1000))
print(x)

[[ 0.14220166 -0.19846715  0.15002695 ... -0.12815113  0.01725476
  -0.07421121]
 [ 0.07065743  0.09505534  0.02669803 ... -0.08851485  0.02206229
  -0.03951231]
 [ 0.01124983  0.10192498 -0.08047    ... -0.06096995  0.02851146
  -0.1003306 ]
 ...
 [-0.01735059 -0.04005159  0.14614774 ...  0.35934247  0.06328049
   0.05460092]
 [ 0.07847172  0.2011379  -0.17484527 ...  0.01666585 -0.08675516
  -0.03815086]
 [ 0.04135794 -0.02900636  0.03106089 ... -0.08708932 -0.25383091
   0.03962335]]


In [43]:
print('mean:', x.mean())
print('std:', x.std())
print('min:', x.min())
print('max:', x.max())
print('# positive:', (x > 0).sum())
print('# negative:', (x < 0).sum())

mean: -4.111053182932829e-05
std: 0.09998464543433597
min: -0.49718326162869214
max: 0.496401683667133
# positive: 499935
# negative: 500065


In [44]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [47]:
print('1st element:', x[0])
print('2nd element:', x[1])
print('5th element:', x[-1])

1st element: 1
2nd element: 2
5th element: 5


In [48]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [49]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print('Element at (0,0)', x[0,0])
print('Element at (0,1)', x[0,1])
print('Element at (2,2)', x[2,2])

Element at (0,0) 1
Element at (0,1) 2
Element at (2,2) 9


In [52]:
# change the o,o element to 20
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [53]:
# delete element, for rank 2 arrays axis 0 used to select row, axis 1 columns
x = np.array([1,2,3,4,5])
print(x)

x = np.delete(x, [0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [55]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

w = np.delete(Y,0,axis=0)
print('\n',w)

v = np.delete(Y,[0,2],axis=1)
print('\n',v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [56]:
x = np.array([1,2,3,4,5])
print(x)

x = np.append(x,6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [57]:
x = np.append(x,[7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [58]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
w = np.append(Y, [[10,11,12]], axis = 0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [60]:
v = np.append(Y, [[10],[11],[12]], axis = 1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [62]:
x = np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [63]:
x = np.insert(x , 2, [3,4])
print(x)

[1 2 3 4 5 6 7]


In [64]:
Y = np.array([[1,2,3], [7,8,9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [65]:
w = np.insert(Y, 1, [4,5,6], axis= 0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
v = np.insert(Y, 1, 5, axis=1)
print(v)

[[1 5 2 3]
 [7 5 8 9]]


In [68]:
# stack arrays vertical or horizontal - shape must match
x = np.array([1,2])
print(x)

Y = np.array([[3,4],[5,6]])
print(Y)

[1 2]
[[3 4]
 [5 6]]


In [70]:
z = np.vstack((x, Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [71]:
# reshape x before stacking
w = np.hstack((Y, x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [72]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [74]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = x[1:4,2:5]
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [75]:
# We can select the same elements as above using method 2
W = x[1:,2:5]
print(W)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [77]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = x[:3,2:5]
print(Y)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [78]:
# We select all the elements in the 3rd row
v = x[2,:]
print(v)

[10 11 12 13 14]


In [80]:
# We select all the elements in the 3rd column
q = x[:,2]
print(q)

[ 2  7 12 17]


In [81]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = x[:,2:3]
print(R)

[[ 2]
 [ 7]
 [12]
 [17]]


The slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. This means that if you make changes in Z you will be in effect changing the elements in X as well. 

In [82]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print(X)

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]
print(Z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [83]:
# We change the last element in Z to 555
Z[2,2] = 555

print(X)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


However, if we want to create a new ndarray that contains a copy of the values in the slice we need to use the np.copy() function. The np.copy(ndarray) function creates a copy of the given ndarray. This function can also be used as a method, in the same way as we did before with the reshape function. 

In [84]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [87]:
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

print('\n',X)
print('\n',Z)
print('\n',W)


 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


It is often useful to use one ndarray to make slices, select, or change elements in another ndarray

In [94]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

print()
print(X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

print()
print(Y)

print()
print(Z)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]


[[ 5  6  7  8  9]
 [15 16 17 18 19]]

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


NumPy also offers built-in functions to select specific elements within ndarrays. For example, the np.diag(ndarray, k=N) function extracts the elements along the diagonal defined by N. As default is k=0, which refers to the main diagonal. Values of k > 0 are used to select elements in diagonals above the main diagonal, and values of k < 0 are used to select elements in diagonals below the main diagonal.

In [89]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5)
print(X)
print()

# We print the elements in the main diagonal of X
print('z =', np.diag(X))
print()

# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))
print()

# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

z = [ 0  6 12 18 24]

y = [ 1  7 13 19]

w =  [ 5 11 17 23]


It is often useful to extract only the unique elements in an ndarray. We can find the unique elements in an ndarray by using the np.unique() function. The np.unique(ndarray) function returns the unique elements in the given ndarray,

In [91]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(X)
print()

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

[[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]


Many situations in which we don't know the indices of the elements we want to select. For example, suppose we have a 10,000 x 10,000 ndarray of random integers ranging from 1 to 15,000 and we only want to select those integers that are less than 20. Boolean indexing can help us in these cases, by allowing us select elements using logical arguments instead of explicit indices.

In [95]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

print()
print(X)

print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

print()
print(X)
print()


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



In addition to Boolean Indexing NumPy also allows for set operations. This useful when comparing ndarrays, for example, to find common elements between two ndarrays. 

In [96]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

print('x:', x)
print('y:', y)
print()

print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

x: [1 2 3 4 5]
y: [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


We can also sort ndarrays in NumPy. When np.sort() is used as a function, it sorts the ndrrays out of place, meaning, that it doesn't change the original ndarray being sorted. However, when you use sort as a method, ndarray.sort() sorts the ndarray in place, meaning, that the original array will be changed to the sorted one

In [97]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))
print()
print(x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


[6 9 5 2 9 2 7 2 9 8]

Sorted x (out of place): [2 2 2 5 6 7 8 9 9 9]

x after sorting: [6 9 5 2 9 2 7 2 9 8]


Notice that np.sort() sorts the array but, if the ndarray being sorted has repeated values, np.sort() leaves those values in the sorted array. However, if desired, we can sort only the unique elements in x by combining the sort function with the unique function.

In [98]:
# We sort x but only keep the unique elements in x
print(np.sort(np.unique(x)))

[2 5 6 7 8 9]


 sort ndarrays in place, by using sort as a method:

In [99]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

print()
print(x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


[10  8  1  1  5  3  1  8  7  7]

x after sorting: [ 1  1  1  3  5  7  7  8  8 10]


When sorting rank 2 ndarrays, we need to specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword.

In [100]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

print()
print(X)

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


[[3 3 4 7 7]
 [3 5 5 3 9]
 [3 8 6 4 7]
 [9 1 2 6 7]
 [7 7 1 1 1]]

X with sorted columns :
 [[3 1 1 1 1]
 [3 3 2 3 7]
 [3 5 4 4 7]
 [7 7 5 6 7]
 [9 8 6 7 9]]

X with sorted rows :
 [[3 3 4 7 7]
 [3 3 5 5 9]
 [3 4 6 7 8]
 [1 2 6 7 9]
 [1 1 1 7 7]]


NumPy sometimes uses something called Broadcasting. Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. For example, broadcasting is used implicitly when doing arithmetic operations between scalars and ndarrays.

NumPy provides a functional approach, where we use functions such as np.add(), or by using arithmetic symbols, such as +, that resembles more how we write mathematical equations. Both forms will do the same operation, the only difference is that if you use the function approach, the functions usually have options that you can tweak using keywords. It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [101]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [102]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


We can also apply mathematical functions, such as sqrt(x), to all elements of an ndarray at once.

In [103]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


Statistical functions provide us with statistical information about the elements in an ndarray.

In [104]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


NumPy can add single numbers to all the elements of an ndarray without the use of complicated loops.

In [105]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In the examples above, NumPy is working behind the scenes to broadcast 3 along the ndarray so that they have the same shape. This allows us to add 3 to each element of X with just one line of code.

Subject to certain constraints, Numpy can do the same for two ndarrays of different shapes, as we can see below.

NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays by broadcasting the smaller ndarrays along the big ndarray so that they have compatible shapes. In general, NumPy can do this provided that the smaller ndarray, such as the 1 x 3 ndarray in our example, can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is unambiguous

In [106]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
